services:
  db:
    container_name: db-mongo
    image: mongo:4.2.23
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - db-mongo:/data/db
  db:
    container_name: db-postgres
    image: postgis/postgis:16-3.4-alpine
    build:
      dockerfile: docker-resources/postgres/Dockerfile.dev
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_ROOT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_BAN_USER=${POSTGRES_BAN_USER}
      - POSTGRES_BAN_PASSWORD=${POSTGRES_BAN_PASSWORD}
    volumes:
      - db-postgres:/var/lib/postgresql/data
  redis:
    # Version of Redis currently in production
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
  api:
    build:
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    networks:
      - ban-plateforme
    depends_on:
      - db-mongo
      - db-postgres
      - redis
    environment:
volumes:
  dist:
  db-mongo:
  db-postgres:
